[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"
include = [ "/rust" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "rust/lib.rs"

[dependencies]
